# Generated by Django 2.0.3 on 2018-07-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='weight',
            new_name='weight_involved',
        ),
    ]
