# Generated by Django 2.0.3 on 2018-07-27 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180726_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='title',
            new_name='name',
        ),
    ]
