# Generated by Django 2.0.3 on 2018-08-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180801_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_focus',
        ),
        migrations.RemoveField(
            model_name='exerciseentry',
            name='exercise',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='ExerciseEntry',
        ),
        migrations.DeleteModel(
            name='ExerciseFocus',
        ),
    ]
