# Generated by Django 2.0.3 on 2018-08-01 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180801_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseentry',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseentry',
            name='miles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseentry',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseentry',
            name='sets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseentry',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='cardio_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CardioType'),
        ),
    ]
