# Generated by Django 2.0.3 on 2018-08-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180801_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseentry',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
