# Generated by Django 2.0.3 on 2018-08-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180801_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseentry',
            name='exercise',
        ),
        migrations.DeleteModel(
            name='ExerciseEntry',
        ),
    ]
