# Generated by Django 2.0.3 on 2018-09-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_exerciseentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='cardio_type',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_focus',
        ),
        migrations.RemoveField(
            model_name='exerciseentry',
            name='exercise',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='ExerciseEntry',
        ),
    ]
